// <auto-generated />
using System;
using HeroManagement.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeroGallery.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230612194656_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HeroManagement.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("HeroManagement.Models.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Power")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Heros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The captain of the Straw Hat Pirates, Luffy has the ability to stretch his body like rubber. He is a fearless and determined fighter who will stop at nothing to become the Pirate King.",
                            Gender = 0,
                            Name = "Monkey D. Luffy",
                            PhotoPath = "/images/luffy.jpg",
                            Power = "Gomu Gomu no Mi (Rubber-Rubber Fruit)",
                            Series = "One Piece"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The main character of the Naruto series, Naruto has the power of the Nine-Tailed Fox sealed inside him. He is a ninja who dreams of becoming the Hokage, the leader of his village.",
                            Gender = 0,
                            Name = "Naruto Uzumaki",
                            PhotoPath = "/images/naruto.jpg",
                            Power = "Nine-Tailed Fox",
                            Series = "Naruto"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A high school student who can see ghosts, Ichigo gains the power of a Soul Reaper and fights to protect his friends and family from evil spirits.",
                            Gender = 0,
                            Name = "Ichigo Kurosaki",
                            PhotoPath = "/images/ichigo.jpg",
                            Power = "Zanpakuto (Soul Slayer)",
                            Series = "Bleach"
                        },
                        new
                        {
                            Id = 4,
                            Description = "A Saiyan warrior from the planet Vegeta, Goku is the main protagonist of the Dragon Ball series. He possesses incredible strength and fighting abilities, and is known for his kind heart and love of adventure.",
                            Gender = 0,
                            Name = "Goku",
                            PhotoPath = "/images/goku.jpg",
                            Power = "Super Saiyan",
                            Series = "Dragon Ball"
                        },
                        new
                        {
                            Id = 5,
                            Description = "A bored and unfulfilled hero who can defeat any opponent with a single punch, Saitama is the protagonist of the One Punch Man series. He seeks to find a worthy opponent who can challenge him.",
                            Gender = 0,
                            Name = "Saitama",
                            PhotoPath = "/images/saitama.jpg",
                            Power = "Superhuman strength",
                            Series = "One Punch Man"
                        },
                        new
                        {
                            Id = 6,
                            Description = "A young alchemist who lost his arm and leg trying to bring his mother back to life, Edward is the main protagonist of the Fullmetal Alchemist series. He and his brother Alphonse search for the Philosopher's Stone to restore their bodies.",
                            Gender = 0,
                            Name = "Edward Elric",
                            PhotoPath = "/images/edward.jpg",
                            Power = "Alchemy",
                            Series = "Fullmetal Alchemist"
                        },
                        new
                        {
                            Id = 7,
                            Description = "A prince of the Britannian Empire who gains the power of Geass, which allows him to control people's minds, Lelouch seeks to overthrow his father and create a better world for his sister Nunnally.",
                            Gender = 0,
                            Name = "Lelouch vi Britannia",
                            PhotoPath = "/images/lelouch.jpg",
                            Power = "Geass (Mind control)",
                            Series = "Code Geass"
                        },
                        new
                        {
                            Id = 8,
                            Description = "A high school student who gains the power to kill anyone whose name he writes in a notebook, Light seeks to create a world free of crime and become its god.",
                            Gender = 0,
                            Name = "Light Yagami",
                            PhotoPath = "/images/light.jpg",
                            Power = "Death Note (Killing notebook)",
                            Series = "Death Note"
                        },
                        new
                        {
                            Id = 9,
                            Description = "A former member of the Uchiha clan who seeks revenge against his brother, Sasuke is a skilled ninja who possesses the Sharingan, a powerful eye technique.",
                            Gender = 0,
                            Name = "Sasuke Uchiha",
                            PhotoPath = "/images/sasuke.jpg",
                            Power = "Sharingan",
                            Series = "Naruto"
                        },
                        new
                        {
                            Id = 10,
                            Description = "A proud and stubborn prince of the Saiyan race, Vegetacontinuing from the previous message...",
                            Gender = 0,
                            Name = "Vegeta",
                            PhotoPath = "/images/vegeta.jpg",
                            Power = "Super Saiyan",
                            Series = "Dragon Ball"
                        },
                        new
                        {
                            Id = 11,
                            Description = "A skilled ninja who serves as the mentor of Naruto and his team, Kakashi possesses the Sharingan and is known for his cool and calm demeanor.",
                            Gender = 1,
                            Name = "Kakashi Hatake",
                            PhotoPath = "/images/kakashi.jpg",
                            Power = "Sharingan",
                            Series = "Naruto"
                        },
                        new
                        {
                            Id = 12,
                            Description = "A young boy who dreams of becoming a Hunter like his father, Gon possesses the power of Nen and sets out on a journey to find his father and become a great Hunter himself.",
                            Gender = 1,
                            Name = "Gon Freecss",
                            PhotoPath = "/images/gon.jpg",
                            Power = "Nen",
                            Series = "Hunter x Hunter"
                        },
                        new
                        {
                            Id = 13,
                            Description = "The former number one hero and the symbol of peace, All Might passes on his power of One For All to Izuku Midoriya and trains him to become the next symbol of peace.",
                            Gender = 1,
                            Name = "All Might",
                            PhotoPath = "/images/allmight.jpg",
                            Power = "One For All",
                            Series = "My Hero Academia"
                        },
                        new
                        {
                            Id = 14,
                            Description = "The captain of the Survey Corps and the strongest soldier in humanity's fight against the Titans, Levi is known for his exceptional combat skills and his clean-freak tendencies.",
                            Gender = 1,
                            Name = "Levi Ackerman",
                            PhotoPath = "/images/levi.jpg",
                            Power = "Omnidirectional Mobility Gear",
                            Series = "Attack on Titan"
                        },
                        new
                        {
                            Id = 15,
                            Description = "A powerful wizard and a member of the Fairy Tail guild, Erza possesses the ability to change her armor and weapons at will using the magic of Requip.",
                            Gender = 1,
                            Name = "Erza Scarlet",
                            PhotoPath = "/images/erza.jpg",
                            Power = "Requip: The Knight",
                            Series = "Fairy Tail"
                        },
                        new
                        {
                            Id = 16,
                            Description = "A delinquent who becomes a Spirit Detective and fights to protect the human world from demons and other supernatural threats, Yusuke possesses the ability to shoot a powerful blast of spirit energy called the Spirit Gun.",
                            Gender = 1,
                            Name = "Yusuke Urameshi",
                            PhotoPath = "/images/yusuke.jpg",
                            Power = "Spirit Gun",
                            Series = "Yu Yu Hakusho"
                        },
                        new
                        {
                            Id = 17,
                            Description = "A former assassin who becomes a wandering swordsman and vows to never kill again, Kenshin is a master of the Hiten Mitsurugi-ryu sword style and uses his skills to protect the innocent.",
                            Gender = 1,
                            Name = "Kenshin Himura",
                            PhotoPath = "/images/kenshin.jpg",
                            Power = "Hiten Mitsurugi-ryu",
                            Series = "Rurouni Kenshin"
                        },
                        new
                        {
                            Id = 18,
                            Description = "A bounty hunter and a former member of a criminal syndicate, Spike is a skilled marksman and a master of hand-to-hand combat. He travels the galaxy with his crew aboard the spaceship Bebop, chasing down the galaxy's most dangerous criminals.",
                            Gender = 1,
                            Name = "Spike Spiegel",
                            PhotoPath = "/images/spike.jpg",
                            Power = "Marksmanship",
                            Series = "Cowboy Bebop"
                        },
                        new
                        {
                            Id = 19,
                            Description = "A high school student who possesses the Millennium Puzzle, Yugi is able to summon powerful monsters to do battle in the shadow realm. He and his friends play a card game called Duel Monsters, which becomes the source of many of their adventures.",
                            Gender = 1,
                            Name = "Yugi Mutou",
                            PhotoPath = "/images/yugi.jpg",
                            Power = "The Millennium Puzzle",
                            Series = "Yu-Gi-Oh!"
                        },
                        new
                        {
                            Id = 20,
                            Description = "A high school student who unknowingly possesses the power to warpreality, Haruhi forms a club with her classmates to search for supernatural beings and phenomena. She is a charismatic and eccentric character who often gets herself and her friends into unusual situations.",
                            Gender = 1,
                            Name = "Haruhi Suzumiya",
                            PhotoPath = "/images/haruhi.jpg",
                            Power = "Reality Warping",
                            Series = "The Melancholy of Haruhi Suzumiya"
                        },
                        new
                        {
                            Id = 21,
                            Description = "A young man who possesses the ability to transform into a Titan, Eren fights to protect humanity from the Titans and uncover the secrets of his own past.",
                            Gender = 1,
                            Name = "Eren Yeager",
                            PhotoPath = "/images/eren.jpg",
                            Power = "Titan Shifter",
                            Series = "Attack on Titan"
                        },
                        new
                        {
                            Id = 22,
                            Description = "A powerful vampire who serves the Hellsing organization, Alucard is a skilled fighter and marksman who uses his supernatural abilities to hunt down and destroy other vampires and supernatural threats.",
                            Gender = 1,
                            Name = "Alucard",
                            PhotoPath = "/images/alucard.jpg",
                            Power = "Vampire",
                            Series = "Hellsing"
                        },
                        new
                        {
                            Id = 23,
                            Description = "A college student who becomes a half-ghoul after a chance encounter with a beautiful woman, Ken struggles to come to terms with his new identity and fights to protect himself and his loved ones from other ghouls and the humans who hunt them.",
                            Gender = 1,
                            Name = "Ken Kaneki",
                            PhotoPath = "/images/kaneki.jpg",
                            Power = "Ghoul",
                            Series = "Tokyo Ghoul"
                        },
                        new
                        {
                            Id = 24,
                            Description = "A member of the Fairy Tail guild and a Dragon Slayer who can manipulate fire, Natsu is a hot-headed and impulsive fighter who always fights for his friends and guildmates.",
                            Gender = 1,
                            Name = "Natsu Dragneel",
                            PhotoPath = "/images/natsu.jpg",
                            Power = "Dragon Slayer Magic",
                            Series = "Fairy Tail"
                        },
                        new
                        {
                            Id = 25,
                            Description = "A young swordsman who joins the Night Raid rebel group, Tatsumi possesses the power of the Incursio armor, which gives him superhuman strength and speed in battle.",
                            Gender = 1,
                            Name = "Tatsumi",
                            PhotoPath = "/images/tatsumi.jpg",
                            Power = "Incursio",
                            Series = "Akame ga Kill!"
                        },
                        new
                        {
                            Id = 26,
                            Description = "A high school student who is taken over by a parasitic alien, Shinichi fights to protect himself and his loved ones from other parasites who seek to take over the world.",
                            Gender = 1,
                            Name = "Shinichi Izumi",
                            PhotoPath = "/images/shinichi.jpg",
                            Power = "Parasite",
                            Series = "Parasyte"
                        },
                        new
                        {
                            Id = 27,
                            Description = "A C-Class hero who rides a bicycle and wears a homemade costume, Mumen Rider has no superpowers but is determined to protect the citizens of his city and fight for justice.",
                            Gender = 1,
                            Name = "Gonpachi",
                            PhotoPath = "/images/mumenrider.jpg",
                            Power = "None",
                            Series = "One Punch Man"
                        },
                        new
                        {
                            Id = 28,
                            Description = "A member of the Hyuga clan who possesses the Byakugan, a powerful eye technique, Hinata is a skilled ninja who overcomes her shyness and fights to protect her friends and loved ones.",
                            Gender = 1,
                            Name = "Hinata Hyuga",
                            PhotoPath = "/images/hinata.jpg",
                            Power = "Byakugan",
                            Series = "Naruto"
                        },
                        new
                        {
                            Id = 29,
                            Description = "A young boy who dreams of becoming a Hunter like his father, Gon possesses the power of Nen and sets out on a journey to find his father and become a great Hunter himself.",
                            Gender = 1,
                            Name = "Gon Freecss",
                            PhotoPath = "/images/gon.jpg",
                            Power = "Nen",
                            Series = "Hunter x Hunter"
                        },
                        new
                        {
                            Id = 30,
                            Description = "A self-proclaimed mad scientist who accidentally discovers the ability to send text messages to the past, Okabe and his friends must navigate the dangers of time travel and the consequences of their actions.",
                            Gender = 1,
                            Name = "Rintaro Okabe",
                            PhotoPath = "/images/okabe.jpg",
                            Power = "Time travel",
                            Series = "Steins;Gate"
                        },
                        new
                        {
                            Id = 31,
                            Description = "A pirate and the captain of the Straw Hat Pirates, Luffy possesses the power of the Gomu Gomu no Mi fruit, which gives him rubber-like abilities and allows him to stretch his body in various ways.",
                            Gender = 1,
                            Name = "Monkey D. Luffy",
                            PhotoPath = "/images/luffy.jpg",
                            Power = "Gomu Gomu no Mi",
                            Series = "One Piece"
                        },
                        new
                        {
                            Id = 32,
                            Description = "A high school student who possesses a sentient uniform named Senketsu, Ryuko fights against the mysterious organization known as Honnouji Academy and their student council president, Satsuki Kiryuin.",
                            Gender = 1,
                            Name = "Ryuko Matoi",
                            PhotoPath = "/images/ryuko.jpg",
                            Power = "Senketsu",
                            Series = "Kill la Kill"
                        },
                        new
                        {
                            Id = 33,
                            Description = "A superhero who can defeat any opponent with a single punch, Saitama is bored with his seemingly endless strength and searches for a worthy opponent.",
                            Gender = 1,
                            Name = "Saitama",
                            PhotoPath = "/images/saitama.jpg",
                            Power = "Superhuman strength and speed",
                            Series = "One Punch Man"
                        },
                        new
                        {
                            Id = 34,
                            Description = "A meister who attends the Death Weapon Meister Academy, Maka possesses the ability to sense the souls of others and uses this ability to help her weapon partner, Soul Eater, collect the souls of evil beings.",
                            Gender = 1,
                            Name = "Maka Albarn",
                            PhotoPath = "/images/maka.jpg",
                            Power = "Soul Perception",
                            Series = "Soul Eater"
                        },
                        new
                        {
                            Id = 35,
                            Description = "A high school student who travels back in time to the feudal era, Kagome possesses the Sacred Jewel and teams up with the half-demon Inuyasha to recover the jewel fragments and prevent evil demons from obtaining its power.",
                            Gender = 1,
                            Name = "Kagome Higurashi",
                            PhotoPath = "/images/kagome.jpg",
                            Power = "Sacred Jewel",
                            Series = "Inuyasha"
                        },
                        new
                        {
                            Id = 36,
                            Description = "A young alchemist who lost his arm and leg in an attempt to bring his mother back to life, Edward and his brother Alphonse search for the Philosopher's Stone in order to restore their bodies.",
                            Gender = 1,
                            Name = "Edward Elric",
                            PhotoPath = "/images/edward.jpg",
                            Power = "Alchemy",
                            Series = "Fullmetal Alchemist"
                        },
                        new
                        {
                            Id = 37,
                            Description = "A young girl who accidentally releases the Clow Cards and must capture them all in order to prevent their destructive power from harming the world, Sakura is a cheerful and determined character who grows stronger as she faces new challenges.",
                            Gender = 1,
                            Name = "Sakura Kinomoto",
                            PhotoPath = "/images/sakura.jpg",
                            Power = "Clow Cards",
                            Series = "Cardcaptor Sakura"
                        },
                        new
                        {
                            Id = 38,
                            Description = "A young chef who attends the prestigious Totsuki Saryo Culinary Institute, Soma uses his creative and unorthodox cooking style to win battles against other talented chefs and rise to the top of the school's hierarchy.",
                            Gender = 1,
                            Name = "Yukihira Soma",
                            PhotoPath = "/images/soma.jpg",
                            Power = "Culinary skills",
                            Series = "Food Wars!"
                        },
                        new
                        {
                            Id = 39,
                            Description = "A young boy who becomes a demon slayer after his family is killed by demons, Tanjirou trains to master the art of Breathing techniques and fights to protect humanity from the demon threat.",
                            Gender = 1,
                            Name = "Tanjirou Kamado",
                            PhotoPath = "/images/tanjirou.jpg",
                            Power = "Breathing techniques",
                            Series = "Demon Slayer"
                        },
                        new
                        {
                            Id = 40,
                            Description = "A minor god who grants wishes for a fee, Yato struggles to gain followers and establish his own shrine. He teams up with a human girl named Hiyori and a regalia named Yukine to complete various tasks and earn money.",
                            Gender = 1,
                            Name = "Yato",
                            PhotoPath = "/images/yato.jpg",
                            Power = "God",
                            Series = "Noragami"
                        },
                        new
                        {
                            Id = 41,
                            Description = "A man who is reincarnated as a slime in a fantasy world, Rimuru gains the ability to absorb other creatures and their abilities. He builds a nation of monsters and allies with various factions to protect his people and make peace with humans.",
                            Gender = 0,
                            Name = "Rimuru Tempest",
                            PhotoPath = "/images/rimuru.jpg",
                            Power = "Absorption",
                            Series = "That Time I Got Reincarnated as a Slime"
                        },
                        new
                        {
                            Id = 42,
                            Description = "A strange creature with a smiling face and tentacles, Koro-sensei is a powerful being who threatens to destroy the Earth. He becomes a teacher for a class of misfit students and teaches them various skills while they try to assassinate him.",
                            Gender = 0,
                            Name = "Koro-sensei",
                            PhotoPath = "/images/korosensei.jpg",
                            Power = "Tentacles",
                            Series = "Assassination Classroom"
                        },
                        new
                        {
                            Id = 43,
                            Description = "An orphan who is adopted by Eren's family, Mikasa becomes a skilled fighter and joins the Survey Corps to avenge her family and protect humanity from the Titans. She wields the omni-directional mobility gear, which allows her to move freely in the air and attack Titans from any direction.",
                            Gender = 1,
                            Name = "Mikasa Ackerman",
                            PhotoPath = "/images/mikasa.jpg",
                            Power = "Omnidirectional Mobility Gear",
                            Series = "Attack on Titan"
                        },
                        new
                        {
                            Id = 44,
                            Description = "A former assassin who has sworn not to kill again, Kenshin becomes a wanderer and helps people in need. He wields a reverse-bladed sword and uses the Hiten Mitsurugi-ryu style, which emphasizes speed and agility in combat.",
                            Gender = 1,
                            Name = "Kenshin Himura",
                            PhotoPath = "/images/kenshin.jpg",
                            Power = "Hiten Mitsurugi-ryu",
                            Series = "Rurouni Kenshin"
                        },
                        new
                        {
                            Id = 45,
                            Description = "A mercenary and former member of the Band of the Hawk, Guts wields a massive sword called the Dragon Slayer and is known for his incredible strength and endurance. He seeks revenge against his former friend and leader, Griffith, who betrayed him and caused the deaths of his comrades.",
                            Gender = 1,
                            Name = "Guts",
                            PhotoPath = "/images/guts.jpg",
                            Power = "Dragon Slayer",
                            Series = "Berserk"
                        },
                        new
                        {
                            Id = 46,
                            Description = "A member of the Lagoon Company, a group of pirates and smugglers, Revy is a skilled gunman who is feared by many. She has a troubled past and a short temper, but also has a softer side that she rarely shows.",
                            Gender = 1,
                            Name = "Revy",
                            PhotoPath = "/images/revy.jpg",
                            Power = "Firearms",
                            Series = "Black Lagoon"
                        },
                        new
                        {
                            Id = 47,
                            Description = "A delinquent who dies saving a child from a car accident, Yusuke becomes a spirit detective and fights against various supernatural threats. He wields the Spirit Gun, a powerful blast of energy that he fires from his index finger.",
                            Gender = 1,
                            Name = "Yusuke Urameshi",
                            PhotoPath = "/images/yusuke.jpg",
                            Power = "Spirit Gun",
                            Series = "Yu Yu Hakusho"
                        },
                        new
                        {
                            Id = 48,
                            Description = "A wild and unpredictable swordsman, Mugen is a former pirate who teams up with a samurai named Jin anda young girl named Fuu to search for the",
                            Gender = 1,
                            Name = "Mugen",
                            PhotoPath = "/images/mugen.jpg",
                            Power = "Swordsmanship",
                            Series = "Samurai Champloo"
                        },
                        new
                        {
                            Id = 49,
                            Description = "A superhero who has become bored with his lack of challenge, Saitama gains immense strength and the ability to defeat any opponent with a single punch. He joins the Hero Association and becomes a mentor to a young cyborg named Genos.",
                            Gender = 1,
                            Name = "Saitama",
                            PhotoPath = "/images/saitama.jpg",
                            Power = "One-Punch",
                            Series = "One-Punch Man"
                        },
                        new
                        {
                            Id = 50,
                            Description = "A young boy who sets out to become a Hunter like his father, Gon has incredible strength and agility, as well as the ability to use Nen, a powerful technique that allows him to manipulate his life energy. He befriends several other aspiring Hunters, including Killua and Leorio.",
                            Gender = 1,
                            Name = "Gon Freecss",
                            PhotoPath = "/images/gon.jpg",
                            Power = "Nen",
                            Series = "Hunter x Hunter"
                        },
                        new
                        {
                            Id = 51,
                            Description = "A normal college student who becomes a half-ghoul after being attacked by one, Kaneki struggles to come to terms with his new identity and the violence that comes with it. He becomes involved in a war between humans and ghouls, and must navigate a complex web of alliances and betrayals.",
                            Gender = 1,
                            Name = "Kaneki Ken",
                            PhotoPath = "/images/kaneki.jpg",
                            Power = "Ghoul",
                            Series = "Tokyo Ghoul"
                        },
                        new
                        {
                            Id = 52,
                            Description = "A pirate and the captain of the Straw Hat Pirates, Luffy gains the ability to stretch his body like rubber after eating a Devil Fruit. He sets out to find the legendary treasure known as One Piece and become the Pirate King, and makes many friends and enemies along the way.",
                            Gender = 1,
                            Name = "Monkey D. Luffy",
                            PhotoPath = "/images/luffy.jpg",
                            Power = "Rubber",
                            Series = "One Piece"
                        },
                        new
                        {
                            Id = 53,
                            Description = "A young alchemist who lost his arm and leg in a failed attempt to bring his mother back to life, Edward sets out with his brother Alphonse to find the Philosopher's Stone, which they believe will allow them to restore their bodies. He is known as the Fullmetal Alchemist due to his automail limbs.",
                            Gender = 1,
                            Name = "Edward Elric",
                            PhotoPath = "/images/edward.jpg",
                            Power = "Alchemy",
                            Series = "Fullmetal Alchemist"
                        },
                        new
                        {
                            Id = 54,
                            Description = "A bounty hunter and former member of the Red Dragon Crime Syndicate, Spike is a skilled fighter and marksman who travels the galaxy with his partner Jet Black in search of the galaxy's most dangerous criminals. He has a troubled past and a love for jazz music.",
                            Gender = 1,
                            Name = "Spike Spiegel",
                            PhotoPath = "/images/spike.jpg",
                            Power = "Hand-to-Hand Combat",
                            Series = "Cowboy Bebop"
                        },
                        new
                        {
                            Id = 55,
                            Description = "A skilled marksman and loyal subordinate of Colonel Roy Mustang, Riza is a member of the military and serves as Mustang's personal assistant and bodyguard. She has a deep commitment to her duties and a troubled past involving her father, who was also a sharpshooter.",
                            Gender = 1,
                            Name = "Riza Hawkeye",
                            PhotoPath = "/images/riza.jpg",
                            Power = "Marksmanship",
                            Series = "Fullmetal Alchemist"
                        },
                        new
                        {
                            Id = 56,
                            Description = "A mysterious girl who serves as the student council president in a purgatory-like afterlife, Kanade is known as Angel due to her supernatural abilities and the fact that she is the only one who can grant the wishes of the students. She develops a connection with the main character, Otonashi, and helps him come to terms with his past.",
                            Gender = 1,
                            Name = "Kanade Tachibana",
                            PhotoPath = "/images/kanade.jpg",
                            Power = "Angel",
                            Series = "Angel Beats!"
                        },
                        new
                        {
                            Id = 57,
                            Description = "A high school student who is infected by a parasite named Migi, Shinichi gains superhuman abilities and finds himself caught in a war between humans and parasites. He develops a complex relationship with Migi as they work together to survive and protect their loved ones.",
                            Gender = 1,
                            Name = "Shinichi Izumi",
                            PhotoPath = "/images/shinichi.jpg",
                            Power = "Migi",
                            Series = "Parasyte"
                        },
                        new
                        {
                            Id = 58,
                            Description = "A member of the Phantom Thieves, a group of high school students who use their supernatural powers to steal the hearts of corrupt adults, Yusuke is a talented artist who discovers his abilities as a Persona user. He struggles to find his place in the world and comes to terms with his complicated family history.",
                            Gender = 1,
                            Name = "Yusuke Kitagawa",
                            PhotoPath = "/images/yusukekitagawa.jpg",
                            Power = "Persona",
                            Series = "Persona 5"
                        },
                        new
                        {
                            Id = 59,
                            Description = "A young girl who discovers a set of magical Clow Cards, Sakura becomes a Cardcaptor and must capture the cards before they cause harm to the world. She has a kind heart and a strong sense of justice, and develops a crush on her friend Syaoran.",
                            Gender = 1,
                            Name = "Sakura Kinomoto",
                            PhotoPath = "/images/sakura.jpg",
                            Power = "Clow Cards",
                            Series = "Cardcaptor Sakura"
                        },
                        new
                        {
                            Id = 60,
                            Description = "A shut-in who dies and is reincarnated in a fantasy world, Kazuma forms a party with a goddess, a mage, and a crusader to defeat the Demon King. He has low stats and relies on his luck and cunning to survive, often getting into comedic and dangerous situations.",
                            Gender = 1,
                            Name = "Kazuma Satou",
                            PhotoPath = "/images/kazuma.jpg",
                            Power = "Luck",
                            Series = "KonoSuba"
                        },
                        new
                        {
                            Id = 61,
                            Description = "A prince who is exiled and gains the power of Geass, which allows him to control people's minds, Lelouch becomes the leader of the rebellion against his father's empire. He is a brilliant strategist and charismatic leader, but his thirst for revenge and desire for power drive him to make questionable decisions.",
                            Gender = 1,
                            Name = "Lelouch Lamperouge",
                            PhotoPath = "/images/lelouch.jpg",
                            Power = "Geass",
                            Series = "Code Geass"
                        },
                        new
                        {
                            Id = 62,
                            Description = "A talented chef who dreams of surpassing his father's skills, Soma enrolls in a prestigious culinary school and competes in various cooking battles. He has a fearless attitude and a creative approach to cooking, often incorporating unusual ingredients and techniques.",
                            Gender = 1,
                            Name = "Soma Yukihira",
                            PhotoPath = "/images/soma.jpg",
                            Power = "Cooking",
                            Series = "Food Wars!"
                        },
                        new
                        {
                            Id = 63,
                            Description = "A high school student who seeks revenge for her father's death, Ryuko discovers a powerful uniform called Kamui that enhances her abilities and grants her superhuman strength and speed. She battles against the student council of her school, which is secretly controlled by her mother.",
                            Gender = 1,
                            Name = "Ryuko Matoi",
                            PhotoPath = "/images/ryuko.jpg",
                            Power = "Kamui",
                            Series = "Kill la Kill"
                        },
                        new
                        {
                            Id = 64,
                            Description = "A high school student who becomes involved with various supernatural beings, Koyomi gains the ability to regenerate any part of his body after being turned into a vampire. He helps various girls with their supernatural problems, often getting into dangerous situations and relying on his wit and charm to get out of them.",
                            Gender = 1,
                            Name = "Koyomi Araragi",
                            PhotoPath = "/images/araragi.jpg",
                            Power = "Regeneration",
                            Series = "Monogatari Series"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "e31d4ac0-129e-4b78-aa0a-d7e57cec96d0",
                            ConcurrencyStamp = "3b6ca02a-71eb-4220-8421-9ee7edc5667e",
                            Name = "USER"
                        },
                        new
                        {
                            Id = "d18ee0c8-c942-4e56-9e53-a5bde475d6d1",
                            ConcurrencyStamp = "5f39fb9a-91ee-4e73-bdc2-979463297216",
                            Name = "ADMIN"
                        },
                        new
                        {
                            Id = "860f6dc8-9cfe-415c-933b-2cfc80160085",
                            ConcurrencyStamp = "8892b604-f159-463a-a817-06514b42f84a",
                            Name = "SUPER ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HeroManagement.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HeroManagement.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeroManagement.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HeroManagement.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
