name: Publish

on: 
  workflow_dispatch:
  push:
    branches: 
    - master
    
jobs:
  publish:
    runs-on: windows-latest
    
    steps: 
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
        
    - name: Restore
      run: dotnet restore ./HeroGallery.sln
      
    - name: Build
      run: dotnet build ./HeroGallery.sln --configuration Release --no-restore
      
    - name: Publish
      run: dotnet publish ./HeroGallery.sln --configuration Release --no-build
    
